<?php

// DO NOT EDIT THIS FILE, MAKE EDITS IN THE .env!!

/*
 * This file is part of uhin/laravel_api.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [

    'pager_duty' => [
        'api_key'               => env('PAGER_DUTY_API_KEY', null),
        'integration_key'       => env('PAGER_DUTY_INTEGRATION_KEY', null),
        'url'                   => env('PAGER_DUTY_URL', 'https://events.pagerduty.com/v2/enqueue'),
        'client'                => env('PAGER_DUTY_CLIENT', config('app.name')),
        'severity'              => env('PAGER_DUTY_SEVERITY', 'info'),
        'action'                => env('PAGER_DUTY_ACTION', 'trigger'),
        'enableserverdetails'   => env('PAGER_DUTY_ENABLE_SERVER_DETAILS', true),
    ],

    'rabbit' => [
        'host'                  => env('RABBIT_HOST', '127.0.0.1'),
        'port'                  => env('RABBIT_PORT', 5672),
        'username'              => env('RABBIT_USERNAME', null),
        'password'              => env('RABBIT_PASSWORD', null),
        'exchange'              => env('RABBIT_EXCHANGE', null),
        'routing_key'           => env('RABBIT_ROUTING_KEY', null),
        'queue'                 => env('RABBIT_QUEUE', null),
    ],

];
